---
title: "data_dmri"
author: "onarvaez"
date: "December 7, 2018"
output:
  pdf_document: default
  html_document: 
    fig_height: 12
    fig_width: 15
---
This documents the function `data_mri()` defined in `data_dmri.R`.
```{r,cache = FALSE}
source("/home/omar/Documents/Tesis/data_mri/data_dmri.R")
knitr::read_chunk("data_dmri.R")
```

This is the function definition
```{r data_dmri}
#cargar y ordenar files
data_dmri <- function(filename1,filename2,y,save,graph){
library(ggplot2)
patha<- ('/home/omar/Documents/Tesis/data_mri/N1/')
pathe<- ('/home/omar/Documents/Tesis/data_mri/N2/')
patho <- ("/home/omar/Documents/Tesis/data_mri/")
file_name_1 <- filename1
file_name_2 <- filename2
eje_y <- y
save_name <- save
graph_name <- graph

absolute_path <- paste(patha,file_name_1,sep = '')

median_data <- (read.delim(absolute_path, sep = ' ', header = FALSE))[2]
ctrl <- (median_data[1:5,][-2])
isq_1 <- (median_data[6:10,])
isq_7 <- (median_data[11:15,])
isq_30 <- (median_data[16:22,][-c(3,5)])

absolute_path_2 <- paste(pathe,file_name_2,sep = '')

median_data <- (read.delim(absolute_path_2, sep = ' ', header = FALSE))[2]
ctrl_b <- (median_data[1:5,][-2])
isq_1_b <- (median_data[6:10,])
isq_7_b <- (median_data[11:15,])
isq_30_b <- (median_data[16:22,][-c(3,5)])

control <- rep('Control', times=4)
un_dia <- rep('Uno', times=5)
siete_dias <- rep('Siete', times=5)
treinta_dias <- rep('Treinta', times=5)

day <- c(control,un_dia,siete_dias,treinta_dias)

intact <- rep('intact', times=19)
damaged <- rep('damaged', times=19)
treat <- c(intact,damaged)

metric <- as.numeric((c(c(ctrl,isq_1,isq_7,isq_30),c(ctrl_b,isq_1_b,isq_7_b,isq_30_b))))
data_pre <- data.frame(metric,day,treat)

#Graficar datos
p <- ggplot(data_pre, aes(x=day, y=metric, fill=treat)) +
  geom_boxplot(position=position_dodge(1)) + 
  labs(title=(paste(file_name_1,'vs',file_name_2)),x="Dias", y = eje_y) +
  geom_jitter(shape=16, position=position_jitter(0.08), aes(colour = treat), size =2.5) +
  scale_x_discrete(limits=c("Control", "Uno", "Siete","Treinta"))
  print(p)
ggsave(graph_name,device = svg)


#pruebas estadísticas

ctrl_test <- as.vector((wilcox.test(ctrl,ctrl_b, paired = F))$p.value)
isq_1_test <- as.vector((wilcox.test(isq_1,isq_1_b, paired = F))$p.value)
isq_7_test <- as.vector((wilcox.test(isq_7,isq_7_b, paired = F))$p.value)
isq_30_test <- as.vector((wilcox.test(isq_30,isq_30_b, paired = F))$p.value)

isq_1_vs_7 <- as.vector((wilcox.test(isq_1,isq_7, paired = F))$p.value)
isq_1_vs_7_b <- as.vector((wilcox.test(isq_1_b,isq_7_b, paired = F))$p.value)
isq_7_vs_30 <- as.vector((wilcox.test(isq_7,isq_30, paired = F))$p.value)
isq_7_vs_30_b <- as.vector((wilcox.test(isq_7_b,isq_30_b, paired = F))$p.value)

pvalues <- c(ctrl_test,isq_1_test,isq_7_test,isq_30_test, isq_1_vs_7,isq_1_vs_7_b, isq_7_vs_30,isq_7_vs_30_b)
names_test <- c('ctrl_test','isq_1_test','isq_7_test','isq_30_test', 'isq_1_vs_7','isq_1_vs_7_b', 'isq_7_vs_30','isq_7_vs_30_b')
p_names <- data.frame(pvalues,names_test)
print(p_names)
write.table(p_names, (paste(patho,save_name, sep = '')),sep = ',')

}

```

##Function test
```{r use_data_dmri}
data_dmri(filename1 = "TENSOR_FA_all_no0_N1.txt",filename2 = "TENSOR_FA_all_no0_N2.txt",y = "FA",save = "prueba.csv",graph = "prueba.svg")
```
